/* SOCKET.IO message Types */
export const PING_SOCKETIO_TYPE = 'PING';
export const PONG_SOCKETIO_TYPE = 'PONG';

export const SERVER_REDIRECTS = [
    TABLE_SOCKETIO_TABLET,
    WEB_SOCKETIO_TABLE,
    TABLET_SOCKETIO_WEB,
    WEB_SOCKETIO_TABLET,
    TABLET_SOCKETIO_WEB,
    TABLET_SOCKETIO_TABLE,
    TABLE_SOCKETIO_WEB
]

export const TABLE_SOCKETIO_TABLET = 'TABLE_TABLET';
export const WEB_SOCKETIO_TABLE = 'WEB_TABLE';
export const TABLE_SOCKETIO_WEB = 'TABLE_WEB';
export const WEB_SOCKETIO_TABLET = 'WEB_TABLET';
export const TABLET_SOCKETIO_TABLE = 'TABLET_TABLE';
export const TABLET_SOCKETIO_WEB = 'TABLET_WEB';
